/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.AbstractListModel;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.WindowConstants;

import models.User;

/**
 *
 * @author Dell Precision
 */
public class AdminWindow extends JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form AdminScreenSW
     */
    public AdminWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jslpAdmin = new JSplitPane();
        jpanAction = new JPanel();
        jpanUser = new JPanel();
        jtfSearchUsers = new JTextField();
        jscrpUserList = new JScrollPane();
        jlUserList = new JList<>();
        jlbSearchUsers = new JLabel();
        jbtnExitUser = new JPanel();
        jlbExitUser = new JLabel();
        jpanProduct = new JPanel();
        jtfSearchProducts = new JTextField();
        jscrpProductList = new JScrollPane();
        jlProductList = new JList<>();
        jlbSearchProducts = new JLabel();
        jbtnExitProduct = new JPanel();
        jlbExitProduct = new JLabel();
        jbtnExpiring = new JButton();
        jpanReport = new JPanel();
        jtfSearchReportedUsers = new JTextField();
        jscrpReportedUsers = new JScrollPane();
        jlReportedUsers = new JList<>();
        jlbSearchReportedUsers = new JLabel();
        jbtnExitReportedUser = new JPanel();
        jlbExitReportedUser = new JLabel();
        jpanSignOut = new JPanel();
        jlbSignOutPrompt = new JLabel();
        jbtnYes = new JButton();
        jpanMenu = new JPanel();
        jlbRentio = new JLabel();
        jbtnUsers = new JPanel();
        jlbUsers = new JLabel();
        jbtnProducts = new JPanel();
        jlbProducts = new JLabel();
        jbtnReportedUsers = new JPanel();
        jlbReportedUsers = new JLabel();
        jbtnSignOut = new JPanel();
        jlbSignOut = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(153, 255, 0));

        jpanAction.setLayout(new CardLayout());

        jpanUser.setBackground(new Color(255, 255, 255));
        jpanUser.setPreferredSize(new Dimension(1000, 800));

        jtfSearchUsers.setBackground(new Color(73, 160, 157));
        jtfSearchUsers.setFont(new Font("Tahoma", 0, 28)); // NOI18N
        jtfSearchUsers.setForeground(new Color(255, 255, 255));
        jtfSearchUsers.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jtfSearchUsersActionPerformed(evt);
            }
        });

        jlUserList.setBorder(BorderFactory.createLineBorder(new Color(39, 64, 70)));
        jlUserList.setFont(new Font("Tahoma", 0, 28)); // NOI18N
        jlUserList.setModel(new AbstractListModel<String>() {
            /**
			 * 
			 */
			private static final long serialVersionUID = 1L;
			String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlUserList.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jlUserListMouseClicked(evt);
            }
        });
        jscrpUserList.setViewportView(jlUserList);

        jlbSearchUsers.setFont(new Font("Tahoma", 0, 30)); // NOI18N
        jlbSearchUsers.setText("Search Users");

        jbtnExitUser.setBackground(new Color(255, 102, 102));
        jbtnExitUser.setForeground(new Color(255, 102, 102));
        jbtnExitUser.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jbtnExitUserMouseClicked(evt);
            }
        });

        jlbExitUser.setFont(new Font("Arial", 0, 30)); // NOI18N
        jlbExitUser.setForeground(new Color(255, 255, 255));
        jlbExitUser.setText("X");

        GroupLayout jbtnExitUserLayout = new GroupLayout(jbtnExitUser);
        jbtnExitUser.setLayout(jbtnExitUserLayout);
        jbtnExitUserLayout.setHorizontalGroup(
            jbtnExitUserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jbtnExitUserLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbExitUser)
                .addContainerGap())
        );
        jbtnExitUserLayout.setVerticalGroup(
            jbtnExitUserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jbtnExitUserLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbExitUser)
                .addContainerGap())
        );

        GroupLayout jpanUserLayout = new GroupLayout(jpanUser);
        jpanUser.setLayout(jpanUserLayout);
        jpanUserLayout.setHorizontalGroup(
            jpanUserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jpanUserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnExitUser, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addGroup(jpanUserLayout.createSequentialGroup()
                .addGroup(jpanUserLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jpanUserLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jscrpUserList, GroupLayout.PREFERRED_SIZE, 901, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanUserLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jlbSearchUsers, GroupLayout.PREFERRED_SIZE, 182, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfSearchUsers)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanUserLayout.setVerticalGroup(
            jpanUserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jpanUserLayout.createSequentialGroup()
                .addComponent(jbtnExitUser, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(jpanUserLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSearchUsers, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSearchUsers))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jscrpUserList, GroupLayout.PREFERRED_SIZE, 700, GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jpanAction.add(jpanUser, "card2");

        jpanProduct.setBackground(new Color(255, 255, 255));

        jtfSearchProducts.setBackground(new Color(73, 160, 157));
        jtfSearchProducts.setFont(new Font("Tahoma", 0, 28)); // NOI18N
        jtfSearchProducts.setForeground(new Color(255, 255, 255));
        jtfSearchProducts.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jtfSearchProductsActionPerformed(evt);
            }
        });

        jlProductList.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        jlProductList.setFont(new Font("Tahoma", 0, 28)); // NOI18N
        jlProductList.setModel(new AbstractListModel<String>() {
            /**
			 * 
			 */
			private static final long serialVersionUID = 1L;
			String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlProductList.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jlProductListMouseClicked(evt);
            }
        });
        jscrpProductList.setViewportView(jlProductList);

        jlbSearchProducts.setFont(new Font("Tahoma", 0, 30)); // NOI18N
        jlbSearchProducts.setText("Search Products");

        jbtnExitProduct.setBackground(new Color(255, 102, 102));
        jbtnExitProduct.setForeground(new Color(255, 102, 102));
        jbtnExitProduct.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jbtnExitProductMouseClicked(evt);
            }
        });

        jlbExitProduct.setFont(new Font("Arial", 0, 30)); // NOI18N
        jlbExitProduct.setForeground(new Color(255, 255, 255));
        jlbExitProduct.setText("X");

        GroupLayout jbtnExitProductLayout = new GroupLayout(jbtnExitProduct);
        jbtnExitProduct.setLayout(jbtnExitProductLayout);
        jbtnExitProductLayout.setHorizontalGroup(
            jbtnExitProductLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jbtnExitProductLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbExitProduct)
                .addContainerGap())
        );
        jbtnExitProductLayout.setVerticalGroup(
            jbtnExitProductLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jbtnExitProductLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbExitProduct)
                .addContainerGap())
        );

        jbtnExpiring.setFont(new Font("Tahoma", 0, 40)); // NOI18N
        jbtnExpiring.setText("Expiring");

        GroupLayout jpanProductLayout = new GroupLayout(jpanProduct);
        jpanProduct.setLayout(jpanProductLayout);
        jpanProductLayout.setHorizontalGroup(
            jpanProductLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jpanProductLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnExitProduct, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addGroup(jpanProductLayout.createSequentialGroup()
                .addGroup(jpanProductLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanProductLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbSearchProducts)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfSearchProducts, GroupLayout.PREFERRED_SIZE, 643, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanProductLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jpanProductLayout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jscrpProductList, GroupLayout.PREFERRED_SIZE, 900, GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpanProductLayout.createSequentialGroup()
                            .addGap(431, 431, 431)
                            .addComponent(jbtnExpiring, GroupLayout.PREFERRED_SIZE, 197, GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jpanProductLayout.setVerticalGroup(
            jpanProductLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jpanProductLayout.createSequentialGroup()
                .addComponent(jbtnExitProduct, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(jpanProductLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jpanProductLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jscrpProductList, GroupLayout.PREFERRED_SIZE, 530, GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jbtnExpiring, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanProductLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfSearchProducts, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlbSearchProducts)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jpanAction.add(jpanProduct, "card3");

        jpanReport.setBackground(new Color(255, 255, 255));

        jtfSearchReportedUsers.setBackground(new Color(73, 160, 157));
        jtfSearchReportedUsers.setFont(new Font("Tahoma", 0, 28)); // NOI18N
        jtfSearchReportedUsers.setForeground(new Color(255, 255, 255));
        jtfSearchReportedUsers.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jtfSearchReportedUsersActionPerformed(evt);
            }
        });

        jlReportedUsers.setBorder(BorderFactory.createLineBorder(new Color(39, 64, 70)));
        jlReportedUsers.setFont(new Font("Tahoma", 0, 28)); // NOI18N
        jlReportedUsers.setModel(new AbstractListModel<String>() {
            /**
			 * 
			 */
			private static final long serialVersionUID = 1L;
			String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlReportedUsers.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jlReportedUsersMouseClicked(evt);
            }
        });
        jscrpReportedUsers.setViewportView(jlReportedUsers);

        jlbSearchReportedUsers.setFont(new Font("Tahoma", 0, 30)); // NOI18N
        jlbSearchReportedUsers.setText("Search Reported Users");

        jbtnExitReportedUser.setBackground(new Color(255, 102, 102));
        jbtnExitReportedUser.setForeground(new Color(255, 102, 102));
        jbtnExitReportedUser.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jbtnExitReportedUserMouseClicked(evt);
            }
        });

        jlbExitReportedUser.setFont(new Font("Arial", 0, 30)); // NOI18N
        jlbExitReportedUser.setForeground(new Color(255, 255, 255));
        jlbExitReportedUser.setText("X");

        GroupLayout jbtnExitReportedUserLayout = new GroupLayout(jbtnExitReportedUser);
        jbtnExitReportedUser.setLayout(jbtnExitReportedUserLayout);
        jbtnExitReportedUserLayout.setHorizontalGroup(
            jbtnExitReportedUserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jbtnExitReportedUserLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbExitReportedUser)
                .addContainerGap())
        );
        jbtnExitReportedUserLayout.setVerticalGroup(
            jbtnExitReportedUserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jbtnExitReportedUserLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbExitReportedUser)
                .addContainerGap())
        );

        GroupLayout jpanReportLayout = new GroupLayout(jpanReport);
        jpanReport.setLayout(jpanReportLayout);
        jpanReportLayout.setHorizontalGroup(
            jpanReportLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jpanReportLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jpanReportLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnExitReportedUser, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGroup(GroupLayout.Alignment.TRAILING, jpanReportLayout.createSequentialGroup()
                        .addGroup(jpanReportLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jscrpReportedUsers, GroupLayout.PREFERRED_SIZE, 900, GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpanReportLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jlbSearchReportedUsers)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfSearchReportedUsers)))
                        .addGap(85, 85, 85))))
        );
        jpanReportLayout.setVerticalGroup(
            jpanReportLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jpanReportLayout.createSequentialGroup()
                .addComponent(jbtnExitReportedUser, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jpanReportLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSearchReportedUsers, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSearchReportedUsers))
                .addGap(80, 80, 80)
                .addComponent(jscrpReportedUsers, GroupLayout.PREFERRED_SIZE, 700, GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jpanAction.add(jpanReport, "card4");

        jpanSignOut.setBackground(new Color(255, 255, 255));

        jlbSignOutPrompt.setFont(new Font("Tahoma", 0, 40)); // NOI18N
        jlbSignOutPrompt.setText("Do you want to sign out?");

        jbtnYes.setFont(new Font("Tahoma", 0, 30)); // NOI18N
        jbtnYes.setText("Yes");
        jbtnYes.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbtnYesActionPerformed(evt);
            }
        });

        GroupLayout jpanSignOutLayout = new GroupLayout(jpanSignOut);
        jpanSignOut.setLayout(jpanSignOutLayout);
        jpanSignOutLayout.setHorizontalGroup(
            jpanSignOutLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jpanSignOutLayout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addGroup(jpanSignOutLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, jpanSignOutLayout.createSequentialGroup()
                        .addComponent(jlbSignOutPrompt)
                        .addGap(296, 296, 296))
                    .addGroup(GroupLayout.Alignment.TRAILING, jpanSignOutLayout.createSequentialGroup()
                        .addComponent(jbtnYes, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE)
                        .addGap(430, 430, 430))))
        );
        jpanSignOutLayout.setVerticalGroup(
            jpanSignOutLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jpanSignOutLayout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(jlbSignOutPrompt)
                .addGap(105, 105, 105)
                .addComponent(jbtnYes, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        jpanAction.add(jpanSignOut, "card5");

        jslpAdmin.setRightComponent(jpanAction);

        jpanMenu.setBackground(new Color(73, 160, 157));

        jlbRentio.setFont(new Font("Roboto", 1, 100)); // NOI18N
        jlbRentio.setForeground(new Color(255, 255, 255));
        jlbRentio.setText("Rentio");

        jbtnUsers.setBackground(new Color(73, 160, 157));
        jbtnUsers.setForeground(new Color(39, 64, 70));
        jbtnUsers.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jbtnUsersMouseClicked(evt);
            }
        });

        jlbUsers.setFont(new Font("Tahoma", 0, 30)); // NOI18N
        jlbUsers.setForeground(new Color(255, 255, 255));
        jlbUsers.setText("For Users");

        GroupLayout jbtnUsersLayout = new GroupLayout(jbtnUsers);
        jbtnUsers.setLayout(jbtnUsersLayout);
        jbtnUsersLayout.setHorizontalGroup(
            jbtnUsersLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jbtnUsersLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbUsers)
                .addGap(117, 117, 117))
        );
        jbtnUsersLayout.setVerticalGroup(
            jbtnUsersLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jbtnUsersLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbUsers)
                .addContainerGap())
        );

        jbtnProducts.setBackground(new Color(73, 160, 157));
        jbtnProducts.setForeground(new Color(39, 64, 70));
        jbtnProducts.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jbtnProductsMouseClicked(evt);
            }
        });

        jlbProducts.setFont(new Font("Tahoma", 0, 30)); // NOI18N
        jlbProducts.setForeground(new Color(255, 255, 255));
        jlbProducts.setText("For Products");

        GroupLayout jbtnProductsLayout = new GroupLayout(jbtnProducts);
        jbtnProducts.setLayout(jbtnProductsLayout);
        jbtnProductsLayout.setHorizontalGroup(
            jbtnProductsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jbtnProductsLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbProducts)
                .addGap(96, 96, 96))
        );
        jbtnProductsLayout.setVerticalGroup(
            jbtnProductsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jbtnProductsLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbProducts)
                .addContainerGap())
        );

        jbtnReportedUsers.setBackground(new Color(73, 160, 157));
        jbtnReportedUsers.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jbtnReportedUsersMouseClicked(evt);
            }
        });

        jlbReportedUsers.setFont(new Font("Tahoma", 0, 30)); // NOI18N
        jlbReportedUsers.setForeground(new Color(255, 255, 255));
        jlbReportedUsers.setText("Reported Users");

        GroupLayout jbtnReportedUsersLayout = new GroupLayout(jbtnReportedUsers);
        jbtnReportedUsers.setLayout(jbtnReportedUsersLayout);
        jbtnReportedUsersLayout.setHorizontalGroup(
            jbtnReportedUsersLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jbtnReportedUsersLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbReportedUsers)
                .addGap(71, 71, 71))
        );
        jbtnReportedUsersLayout.setVerticalGroup(
            jbtnReportedUsersLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jbtnReportedUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbReportedUsers, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnSignOut.setBackground(new Color(73, 160, 157));
        jbtnSignOut.setForeground(new Color(39, 64, 70));
        jbtnSignOut.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jbtnSignOutMouseClicked(evt);
            }
        });

        jlbSignOut.setFont(new Font("Tahoma", 0, 30)); // NOI18N
        jlbSignOut.setForeground(new Color(255, 255, 255));
        jlbSignOut.setText("Sign Out");

        GroupLayout jbtnSignOutLayout = new GroupLayout(jbtnSignOut);
        jbtnSignOut.setLayout(jbtnSignOutLayout);
        jbtnSignOutLayout.setHorizontalGroup(
            jbtnSignOutLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jbtnSignOutLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbSignOut)
                .addGap(115, 115, 115))
        );
        jbtnSignOutLayout.setVerticalGroup(
            jbtnSignOutLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jbtnSignOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbSignOut)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout jpanMenuLayout = new GroupLayout(jpanMenu);
        jpanMenu.setLayout(jpanMenuLayout);
        jpanMenuLayout.setHorizontalGroup(
            jpanMenuLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jbtnUsers, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpanMenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jlbRentio)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jbtnProducts, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtnReportedUsers, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtnSignOut, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpanMenuLayout.setVerticalGroup(
            jpanMenuLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jpanMenuLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jlbRentio, GroupLayout.PREFERRED_SIZE, 235, GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jbtnUsers, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jbtnProducts, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jbtnReportedUsers, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jbtnSignOut, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jslpAdmin.setLeftComponent(jpanMenu);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jslpAdmin, GroupLayout.DEFAULT_SIZE, 1391, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jslpAdmin, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnUsersMouseClicked(MouseEvent evt) {//GEN-FIRST:event_jbtnUsersMouseClicked
        // TODO add your handling code here:
        jpanAction.removeAll();
        jpanAction.repaint();
        jpanAction.revalidate();

        jpanAction.add(jpanUser);
        jpanAction.repaint();
        jpanAction.revalidate();
    }//GEN-LAST:event_jbtnUsersMouseClicked

    private void jbtnReportedUsersMouseClicked(MouseEvent evt) {//GEN-FIRST:event_jbtnReportedUsersMouseClicked
        // TODO add your handling code here:
        jpanAction.removeAll();
        jpanAction.repaint();
        jpanAction.revalidate();

        jpanAction.add(jpanReport);
        jpanAction.repaint();
        jpanAction.revalidate();
    }//GEN-LAST:event_jbtnReportedUsersMouseClicked

    private void jlUserListMouseClicked(MouseEvent evt) {//GEN-FIRST:event_jlUserListMouseClicked
        // TODO add your handling code here:

        UserDetailWindow userDetail = new UserDetailWindow();
        userDetail.setVisible(true);
    }//GEN-LAST:event_jlUserListMouseClicked

    private void jlProductListMouseClicked(MouseEvent evt) {//GEN-FIRST:event_jlProductListMouseClicked
        // TODO add your handling code here:

        ProductDetailWindow productDetail = new ProductDetailWindow();
        productDetail.setVisible(true);
    }//GEN-LAST:event_jlProductListMouseClicked

    private void jbtnExitUserMouseClicked(MouseEvent evt) {//GEN-FIRST:event_jbtnExitUserMouseClicked
        // TODO add your handling code here:
    	jpanAction.removeAll();
        jpanAction.repaint();
        jpanAction.revalidate();
    }//GEN-LAST:event_jbtnExitUserMouseClicked

    private void jlReportedUsersMouseClicked(MouseEvent evt) {//GEN-FIRST:event_jlReportedUsersMouseClicked
        // TODO add your handling code here:
        ReportedUsersWindow reportedUser = new ReportedUsersWindow();
        reportedUser.setVisible(true);
    }//GEN-LAST:event_jlReportedUsersMouseClicked

    private void jbtnExitReportedUserMouseClicked(MouseEvent evt) {//GEN-FIRST:event_jbtnExitReportedUserMouseClicked
        // TODO add your handling code here:
    	jpanAction.removeAll();
        jpanAction.repaint();
        jpanAction.revalidate();
    }//GEN-LAST:event_jbtnExitReportedUserMouseClicked

    private void jtfSearchReportedUsersActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jtfSearchReportedUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSearchReportedUsersActionPerformed

    private void jbtnExitProductMouseClicked(MouseEvent evt) {//GEN-FIRST:event_jbtnExitProductMouseClicked
        // TODO add your handling code here:
    	jpanAction.removeAll();
        jpanAction.repaint();
        jpanAction.revalidate();
    }//GEN-LAST:event_jbtnExitProductMouseClicked

    private void jtfSearchProductsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jtfSearchProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSearchProductsActionPerformed

    private void jbtnSignOutMouseClicked(MouseEvent evt) {//GEN-FIRST:event_jbtnSignOutMouseClicked
        // TODO add your handling code here:
        //this.hide();
        //LoginSW LS= new LoginSW();
        //LS.setVisible(true);
        jpanAction.removeAll();
        jpanAction.repaint();
        jpanAction.revalidate();

        jpanAction.add(jpanSignOut);
        jpanAction.repaint();
        jpanAction.revalidate();
    }//GEN-LAST:event_jbtnSignOutMouseClicked

    private void jbtnYesActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbtnYesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LogInWindow login = new LogInWindow();
        login.setVisible(true);
    }//GEN-LAST:event_jbtnYesActionPerformed

    private void jbtnProductsMouseClicked(MouseEvent evt) {//GEN-FIRST:event_jbtnProductsMouseClicked
        // TODO add your handling code here:
        jpanAction.removeAll();
        jpanAction.repaint();
        jpanAction.revalidate();

        jpanAction.add(jpanProduct);
        jpanAction.repaint();
        jpanAction.revalidate();
    }//GEN-LAST:event_jbtnProductsMouseClicked

    private void jtfSearchUsersActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jtfSearchUsersActionPerformed
        // TODO add your handling code here:
    	List<User> userList = new ArrayList<User>();
    	
    	try (Connection connection = DriverManager.getConnection(
    			"jdbc:postgresql://localhost:5432/rentio", "postgres", "sesame")) {
    		Statement stmt = connection.createStatement();
    		String sql = String.format(
    				"SELECT * FROM users WHERE first_name = '%s';", 
    				jtfSearchUsers.getText());
    		ResultSet rs = stmt.executeQuery(sql);
    		while (rs.next()) {
    			Map<String, String> userFromDB = new HashMap<String, String>();
    			userFromDB.put("id", rs.getString("id"));
    			userFromDB.put("first_name", rs.getString("first_name"));
    			userFromDB.put("last_name", rs.getString("last_name"));
    			userFromDB.put("gender", rs.getString("gender"));
    			userFromDB.put("birthday", rs.getString("birthday"));
    			userFromDB.put("email", rs.getString("email"));
    			userFromDB.put("username", rs.getString("username"));
    			userFromDB.put("password", rs.getString("password"));
    			userFromDB.put("phone", rs.getString("phone"));
    			userFromDB.put("address", rs.getString("address"));
    			userFromDB.put("job", rs.getString("job"));
    			userFromDB.put("free_trial_start", rs.getString("free_trial_start"));
    			userFromDB.put("free_trial_end", rs.getString("free_trial_end"));
    			
    			userList.add(new User(userFromDB));
    		}
    	}
    	catch (SQLException exc) {
    		System.err.format("SQL State: %s\n%s", exc.getSQLState(), exc.getMessage());
    	}
    	catch (Exception exc) {
    		exc.printStackTrace();
    	}
    }//GEN-LAST:event_jtfSearchUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(AdminWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(AdminWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(AdminWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel jlbUsers;
    private JPanel jbtnExitProduct;
    private JPanel jbtnExitReportedUser;
    private JPanel jbtnExitUser;
    private JButton jbtnExpiring;
    private JPanel jbtnProducts;
    private JPanel jbtnReportedUsers;
    private JPanel jbtnSignOut;
    private JPanel jbtnUsers;
    private JButton jbtnYes;
    private JList<String> jlProductList;
    private JList<String> jlReportedUsers;
    private JList<String> jlUserList;
    private JLabel jlbExitProduct;
    private JLabel jlbExitReportedUser;
    private JLabel jlbExitUser;
    private JLabel jlbProducts;
    private JLabel jlbRentio;
    private JLabel jlbReportedUsers;
    private JLabel jlbSearchProducts;
    private JLabel jlbSearchReportedUsers;
    private JLabel jlbSearchUsers;
    private JLabel jlbSignOut;
    private JLabel jlbSignOutPrompt;
    private JPanel jpanAction;
    private JPanel jpanMenu;
    private JPanel jpanProduct;
    private JPanel jpanReport;
    private JPanel jpanSignOut;
    private JPanel jpanUser;
    private JScrollPane jscrpProductList;
    private JScrollPane jscrpReportedUsers;
    private JScrollPane jscrpUserList;
    private JSplitPane jslpAdmin;
    private JTextField jtfSearchProducts;
    private JTextField jtfSearchReportedUsers;
    private JTextField jtfSearchUsers;
    // End of variables declaration//GEN-END:variables
}
