/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Font;

/**
 *
 * @author Dell Precision
 */
public class LogInWindow extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form LoginSW
     */
    public LogInWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jslpLogIn = new javax.swing.JSplitPane();
        jpanLogo = new javax.swing.JPanel();
        jlbRentio = new javax.swing.JLabel();
        jpanAction = new javax.swing.JPanel();
        jpanSignInDetail = new javax.swing.JPanel();
        jtfPassword = new javax.swing.JTextField();
        jtfUsername = new javax.swing.JTextField();
        jbtnLogin = new javax.swing.JButton();
        jlbPassword = new javax.swing.JLabel();
        jlbUsername = new javax.swing.JLabel();
        jlbLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanLogo.setBackground(new java.awt.Color(73, 160, 157));

        jlbRentio.setFont(new Font("Dialog", Font.BOLD, 90)); // NOI18N
        jlbRentio.setForeground(new java.awt.Color(255, 255, 255));
        jlbRentio.setText("Rentio");

        javax.swing.GroupLayout jpanLogoLayout = new javax.swing.GroupLayout(jpanLogo);
        jpanLogo.setLayout(jpanLogoLayout);
        jpanLogoLayout.setHorizontalGroup(
            jpanLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanLogoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jlbRentio, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jpanLogoLayout.setVerticalGroup(
            jpanLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanLogoLayout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(jlbRentio, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(454, Short.MAX_VALUE))
        );

        jslpLogIn.setLeftComponent(jpanLogo);

        jpanAction.setLayout(new java.awt.CardLayout());

        jpanSignInDetail.setBackground(new java.awt.Color(255, 255, 255));

        jtfPassword.setBackground(new java.awt.Color(73, 160, 157));
        jtfPassword.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jtfPassword.setForeground(new java.awt.Color(255, 255, 255));

        jtfUsername.setBackground(new java.awt.Color(73, 160, 157));
        jtfUsername.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jtfUsername.setForeground(new java.awt.Color(255, 255, 255));

        jbtnLogin.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnLoginMouseClicked(evt);
            }
        });

        jlbPassword.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jlbPassword.setText("Password");

        jlbUsername.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jlbUsername.setText("User Name");

        jlbLogin.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        jlbLogin.setText("Log In");

        javax.swing.GroupLayout jpanSignInDetailLayout = new javax.swing.GroupLayout(jpanSignInDetail);
        jpanSignInDetail.setLayout(jpanSignInDetailLayout);
        jpanSignInDetailLayout.setHorizontalGroup(
            jpanSignInDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanSignInDetailLayout.createSequentialGroup()
                .addGroup(jpanSignInDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanSignInDetailLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jpanSignInDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanSignInDetailLayout.createSequentialGroup()
                                .addComponent(jlbPassword)
                                .addGap(89, 89, 89)
                                .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanSignInDetailLayout.createSequentialGroup()
                                .addComponent(jlbUsername)
                                .addGap(68, 68, 68)
                                .addGroup(jpanSignInDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbLogin)
                                    .addComponent(jtfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jpanSignInDetailLayout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jpanSignInDetailLayout.setVerticalGroup(
            jpanSignInDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanSignInDetailLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jlbLogin)
                .addGap(111, 111, 111)
                .addGroup(jpanSignInDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbUsername)
                    .addComponent(jtfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jpanSignInDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbPassword))
                .addGap(79, 79, 79)
                .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        jpanAction.add(jpanSignInDetail, "card2");

        jslpLogIn.setRightComponent(jpanAction);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jslpLogIn)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jslpLogIn)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnLoginMouseClicked
        // TODO add your handling code here:
    	String username = jtfUsername.getText();
    	String password = jtfPassword.getText();
    	
    	try (Connection connection = DriverManager.getConnection(
    			"jdbc:postgresql://localhost:5432/rentio", "postgres", "sesame")) {
    		Statement stmt = connection.createStatement();
    		ResultSet rs = stmt.executeQuery("SELECT username, password FROM admins;");
    		while (rs.next()) {
    			if (username.equals(rs.getString("username")) & 
    					password.equals(rs.getString("password"))) {
    				JOptionPane.showMessageDialog(new JFrame(), "Log in successfully", "Success", JOptionPane.OK_OPTION);
    				this.setVisible(false);
    		        AdminWindow adminScreen = new AdminWindow();
    		        adminScreen.setVisible(true);
    		        return;
    			}
    		}
    		
    		throw new InvalidUserException();
    	} 
    	catch (InvalidUserException exc) {
    		JOptionPane.showMessageDialog(new JFrame(), exc, "Failed", JOptionPane.ERROR_MESSAGE);
    	}
    	catch (SQLException exc) {
    		System.err.format("SQL State: %s\n%s", exc.getSQLState(), exc.getMessage());
    	}
    	catch (Exception exc) {
    		exc.printStackTrace();
    	}
    }//GEN-LAST:event_jbtnLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JLabel jlbLogin;
    private javax.swing.JLabel jlbPassword;
    private javax.swing.JLabel jlbRentio;
    private javax.swing.JLabel jlbUsername;
    private javax.swing.JPanel jpanAction;
    private javax.swing.JPanel jpanLogo;
    private javax.swing.JPanel jpanSignInDetail;
    private javax.swing.JSplitPane jslpLogIn;
    private javax.swing.JTextField jtfPassword;
    private javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables
}
