/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

import models.User;

/**
 *
 * @author Dell Precision
 */
public class UserDetailWindow extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form UserDetail
     */
    public UserDetailWindow(User user) {
        initComponents(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(User user) {
    	setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    	
        jpanUserDetail = new javax.swing.JPanel();
        jtfSex = new JTextField(user.getGender());
        jtfPhoneNumber = new JTextField(user.getPhone());
        jtfName = new JTextField(user.getFirstName() + " " + user.getLastName());
        jtfUserID = new JTextField(user.getID());
        jtfBirthday = new JTextField(user.getBirthday());
        jlbUserID = new JLabel();
        jlbBirthday = new JLabel();
        jlbPhoneNumber = new JLabel();
        jlbSex = new JLabel();
        jlbName = new JLabel();
        jbtnDeleteUser = new JButton();
        jbtnBack = new JButton();
        jbtnSave = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(255, 255, 255));
        setForeground(Color.white);

        jpanUserDetail.setBackground(new Color(255, 255, 255));

        jlbUserID.setFont(new Font("Tahoma", 0, 28)); // NOI18N
        jlbUserID.setText("User ID");

        jlbBirthday.setFont(new Font("Tahoma", 0, 28)); // NOI18N
        jlbBirthday.setText("Birthday");

        jlbPhoneNumber.setFont(new Font("Tahoma", 0, 28)); // NOI18N
        jlbPhoneNumber.setText("Phone Number");

        jlbSex.setFont(new Font("Tahoma", 0, 28)); // NOI18N
        jlbSex.setText("Gender ");

        jlbName.setFont(new Font("Tahoma", 0, 28)); // NOI18N
        jlbName.setText("Name ");

        jbtnDeleteUser.setBackground(new Color(255, 255, 255));
        jbtnDeleteUser.setFont(new Font("Tahoma", 0, 28)); // NOI18N
        jbtnDeleteUser.setText("Delete");
        jbtnDeleteUser.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbtnDeleteUserActionPerformed(evt);
            }
        });

        jbtnBack.setFont(new Font("Tahoma", 0, 28)); // NOI18N
        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jbtnSave.setFont(new Font("Tahoma", 0, 28)); // NOI18N
        jbtnSave.setText("Save");
        jbtnSave.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jbtnSaveActionPerformed(evt);
			}
		});

        javax.swing.GroupLayout jpanUserDetailLayout = new GroupLayout(jpanUserDetail);
        jpanUserDetail.setLayout(jpanUserDetailLayout);
        jpanUserDetailLayout.setHorizontalGroup(
            jpanUserDetailLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jpanUserDetailLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jpanUserDetailLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jlbName, GroupLayout.PREFERRED_SIZE, 196, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbUserID, GroupLayout.PREFERRED_SIZE, 196, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbBirthday, GroupLayout.PREFERRED_SIZE, 196, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSex, GroupLayout.PREFERRED_SIZE, 196, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbPhoneNumber, GroupLayout.PREFERRED_SIZE, 196, GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addGroup(jpanUserDetailLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jtfName, GroupLayout.PREFERRED_SIZE, 394, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfUserID, GroupLayout.PREFERRED_SIZE, 394, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfBirthday, GroupLayout.PREFERRED_SIZE, 394, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSex, GroupLayout.PREFERRED_SIZE, 394, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPhoneNumber, GroupLayout.PREFERRED_SIZE, 394, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, jpanUserDetailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnDeleteUser, GroupLayout.PREFERRED_SIZE, 207, GroupLayout.PREFERRED_SIZE)
                .addGap(360, 360, 360))
            .addGroup(jpanUserDetailLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jbtnBack, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnSave, GroupLayout.PREFERRED_SIZE, 141, GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        jpanUserDetailLayout.setVerticalGroup(
            jpanUserDetailLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jpanUserDetailLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jpanUserDetailLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnBack, GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jbtnSave, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addGroup(jpanUserDetailLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbUserID, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfUserID, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanUserDetailLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbName, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfName, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanUserDetailLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jtfBirthday, GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbBirthday, GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanUserDetailLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSex, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSex, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanUserDetailLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPhoneNumber, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPhoneNumber, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jbtnDeleteUser, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jpanUserDetail, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanUserDetail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBackActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed
    
    private void jbtnDeleteUserActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteUserActionPerformed
        // TODO add your handling code here:
        try (Connection connection = DriverManager.getConnection(
        		"jdbc:postgresql://localhost:5432/rentio", "postgres", "sesame")){
        	
        }
        catch (SQLException exc) {
    		System.err.format("SQL State: %s\n%s", exc.getSQLState(), exc.getMessage());
    	}
    	catch (Exception exc) {
    		exc.printStackTrace();
    	}
    }//GEN-LAST:event_jbtnDeleteUserActionPerformed
    
    private void jbtnSaveActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbtnSaveActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jbtnBack;
    private JButton jbtnDeleteUser;
    private JButton jbtnSave;
    private JLabel jlbBirthday;
    private JLabel jlbName;
    private JLabel jlbPhoneNumber;
    private JLabel jlbSex;
    private JLabel jlbUserID;
    private JPanel jpanUserDetail;
    private JTextField jtfBirthday;
    private JTextField jtfName;
    private JTextField jtfPhoneNumber;
    private JTextField jtfSex;
    private JTextField jtfUserID;
    // End of variables declaration//GEN-END:variables
}
